### ISSUE TITLE
Extension violates webstore's policy

### ISSUE THREAD

**Issue by hrishikesh-deshpande** [AshBardhan/memefy-this#16]
Extension was disabled by chrome and is removed by webstore. What exactly is the issue?

**Comment by AshBardhan** [comment]
I've been notified by chrome team via mail. According to their latest policy - Since there is no updates in the my extension for a long period of time, my extension has been taken down. Don't worry - I'll plan to have a small update very soon.

Meanwhile, you can still clone the repo and run this extension on your browser.
